spring.data.mongodb.uri = mongodb+srv://johnmessoa:Nirvanaq123@cluster0.fqj18d4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database = InVx
spring.data.mongodb.auto-index-creation=true

spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 200MB
spring.servlet.multipart.max-request-size = 200MB



jwtSecret = 1234howmanynwahsAREinMYstoreIknoooooooooowytoustelkng
jwtExpirationMs = 8640000
jwtCookieName = InVx
